# scripts/tag_display_map.py
# Tag 显示名称映射配置
# 用于统一股票卡片上标签的显示名称

TAG_DISPLAY_MAP = {
    # ===== 第三代半导体 =====
    "SiC": "碳化硅 (SiC)",
    "碳化硅": "碳化硅 (SiC)",
    "SiC衬底": "碳化硅衬底 (SiC)",
    "碳化硅衬底": "碳化硅衬底 (SiC)",
    "GaN": "氮化镓 (GaN)",
    "氮化镓": "氮化镓 (GaN)",
    "GaN衬底": "氮化镓衬底 (GaN)",
    "GaAs": "砷化镓 (GaAs)",
    "砷化镓": "砷化镓 (GaAs)",
    "InP": "磷化铟 (InP)",
    "磷化铟": "磷化铟 (InP)",
    "化合物半导体": "化合物半导体",
    
    # ===== 先进封装 =====
    "2.5D": "2.5D封装",
    "2.5D封装": "2.5D封装",
    "3D": "3D封装",
    "3D封装": "3D封装",
    "CoWoS": "CoWoS (晶圆级封装)",
    "SiP": "SiP (系统级封装)",
    "FC-BGA": "FC-BGA (倒装芯片球栅阵列)",
    "ABF": "ABF (先进封装基板)",
    "ABF载板": "ABF载板",
    "SoIC": "SoIC (集成芯片系统)",
    "FOPLP": "FOPLP (面板级封装)",
    "FO-WLP": "FO-WLP (晶圆级扇出封装)",
    "Hybrid Bonding": "混合键合 (Hybrid Bonding)",
    "晶圆级封装": "晶圆级封装",
    "系统级封装": "系统级封装 (SiP)",
    "异构封装": "异构封装 (Heterogeneous Integration)",
    "Chiplet": "Chiplet (小芯片)",
    
    # ===== 半导体设备 =====
    "ALD": "ALD (原子层沉积)",
    "CVD": "CVD (化学气相沉积)",
    "PVD": "PVD (物理气相沉积)",
    "MOCVD": "MOCVD (金属有机化学气相沉积)",
    "刻蚀": "刻蚀 (Etch)",
    "沉积": "薄膜沉积 (Deposition)",
    "热处理": "热处理 (Thermal)",
    "离子注入": "离子注入 (Ion Implantation)",
    "量测": "量测 (Metrology)",
    "检测": "检测 (Inspection)",
    "ATE": "ATE (自动测试设备)",
    "EUV": "EUV (极紫外光刻)",
    "DUV": "DUV (深紫外光刻)",
    "NIL": "NIL (纳米压印光刻)",
    
    # ===== 半导体材料 =====
    "硅晶圆": "硅晶圆 (Wafer)",
    "SOI硅片": "SOI硅片",
    "外延片": "外延片 (Epitaxial Wafer)",
    "光刻胶": "光刻胶 (Photoresist)",
    "EUV光刻胶": "EUV光刻胶",
    "ArF光刻胶": "ArF光刻胶",
    "光掩膜": "光掩膜 (Mask)",
    "光掩模": "光掩膜 (Mask)",
    "Mask": "光掩膜 (Mask)",
    "Mask Blank": "光刻基板 (Mask Blank)",
    "光刻基板": "光刻基板 (Mask Blank)",
    "CMP": "CMP (化学机械抛光)",
    "CMP抛光垫": "CMP抛光垫",
    "CMP浆料": "CMP浆料",
    "MLCC": "MLCC (多层陶瓷电容)",
    "EMC": "EMC (环氧塑封料)",
    "EMC塑封料": "EMC塑封料",
    
    # ===== 算力芯片 =====
    "GPU": "GPU (图形处理器)",
    "CPU": "CPU (中央处理器)",
    "ASIC": "ASIC (专用集成电路)",
    "FPGA": "FPGA (现场可编程门阵列)",
    "AI SoC": "AI SoC (系统级芯片)",
    "MCU": "MCU (微控制器)",
    "NPU": "NPU (神经网络处理器)",
    "DPU": "DPU (数据处理器)",
    "DSP": "DSP (数字信号处理器)",
    "RISC-V": "RISC-V (开源指令集)",
    "HBM": "HBM (高带宽内存)",
    "HBM3": "HBM3 (高带宽内存)",
    "HBM3E": "HBM3E (高带宽内存)",
    "HBM4": "HBM4 (高带宽内存)",
    "DRAM": "DRAM (动态随机存取内存)",
    "SRAM": "SRAM (静态随机存取内存)",
    "DDR5": "DDR5 (第五代内存)",
    "NAND Flash": "NAND Flash (闪存)",
    "内存接口": "内存接口 (Memory Interface)",
    "CXL": "CXL (Compute Express Link)",
    
    # ===== 光通信 =====
    "光模块": "光模块 (Optical Transceiver)",
    "光芯片": "光芯片 (Optical Chip)",
    "光纤光缆": "光纤光缆 (Fiber Optic)",
    "硅光子": "硅光子 (Silicon Photonics)",
    "CPO": "CPO (光电共封装)",
    "CPO光电共封装": "CPO (光电共封装)",
    "EML": "EML (电吸收调制激光器)",
    "VCSEL": "VCSEL (垂直腔面发射激光器)",
    "DFB": "DFB (分布反馈激光器)",
    "800G": "800G (光模块)",
    "1.6T": "1.6T (光模块)",
    
    # ===== 电力・液冷・数据中心 =====
    "UPS": "UPS (不间断电源)",
    "PDU": "PDU (电源分配单元)",
    "CDU": "CDU (冷量分配单元)",
    "HVAC": "HVAC (暖通空调)",
    "液冷": "液冷 (Liquid Cooling)",
    "浸没液冷": "浸没液冷",
    "冷板": "冷板液冷",
    "服务器": "服务器 (Server)",
    "AI服务器": "AI服务器",
    "HPC": "HPC (高性能计算)",
    "机柜": "机柜 (Rack)",
    "数据中心": "数据中心 (IDC)",
    "储能": "储能 (Energy Storage)",
    "蓄电池": "蓄电池 (Battery)",
    "储能电池": "储能电池",
    "核电": "核电 (Nuclear Power)",
    
    # ===== 工业自动化与机器人 =====
    "CNC": "CNC (数控系统)",
    "PLC": "PLC (可编程逻辑控制器)",
    "IIoT": "IIoT (工业物联网)",
    "MES": "MES (制造执行系统)",
    "FA自动化": "FA (工厂自动化)",
    
    # ===== 云・AI应用 =====
    "Azure": "Azure (微软云)",
    "AWS": "AWS (亚马逊云)",
    "Google Cloud": "Google Cloud (谷歌云)",
    "Gemini": "Gemini (谷歌大模型)",
    "TPU": "TPU (张量处理器)",
    "IP授权": "IP授权 (Intellectual Property)",
}
