# scripts/tag_display_map.py
# Tag 显示名称映射配置（只保留映射前后不一样的条目）

TAG_DISPLAY_MAP = {
    # ===== 第三代半导体 =====
    "SiC": "碳化硅 (SiC)",
    "SiC衬底": "碳化硅衬底 (SiC)",
    "碳化硅衬底", "碳化硅衬底 (SiC)"
    "GaN": "氮化镓 (GaN)",
    "氮化镓": "氮化镓 (GaN)",
    "GaN衬底": "氮化镓衬底 (GaN)",
    "氮化镓衬底": "氮化镓衬底 (GaN)",
    "GaAs": "砷化镓 (GaAs)",
    "砷化镓": "砷化镓 (GaAs)",
    "InP": "磷化铟 (InP)",
    "磷化铟": "磷化铟 (InP)",
    # ===== 先进封装 =====
    "2.5D": "2.5D封装",
    "3D": "3D封装",
    "CoWoS": "CoWoS (晶圆级封装)",
    "SiP": "SiP (系统级封装)",
    "FC-BGA": "FC-BGA (倒装芯片球栅阵列)",
    "SoIC": "SoIC (集成芯片系统)",
    "FOPLP": "FOPLP (面板级封装)",
    "FO-WLP": "FO-WLP (晶圆级扇出封装)",
    "Hybrid Bonding": "混合键合 (Hybrid Bonding)",
    "异构封装": "异构封装 (Heterogeneous Integration)",
    "Chiplet": "Chiplet (小芯片)",
    
    # ===== 半导体设备 =====
    "DUV": "DUV (深紫外光刻)",
    "EUV": "EUV (极紫外光刻)",
    "NIL": "NIL (纳米压印光刻)",
    "ArF": "ArF (氟化氩激光)",
    "KrF": "KrF (氟化氪激光)",
    "ICP": "ICP (电感耦合等离子体刻蚀)",
    "CCP": "CCP (电容耦合等离子体刻蚀)",
    "RIE": "RIE (反应离子刻蚀)",
    "DRIE": "DRIE (深反应离子刻蚀)",
    "CVD": "CVD (化学气相沉积)",
    "PVD": "PVD (物理气相沉积)",
    "ALD": "ALD (原子层沉积)",
    "MOCVD": "MOCVD (金属有机化学气相沉积)",
    "LPCVD": "LPCVD (低压化学气相沉积)",
    "PECVD": "PECVD (等离子体增强化学气相沉积)",
    "CMP": "CMP (化学机械抛光)",
    "Mask Writer": "光罩描画 (Mask Writer)",
    "SEM": "SEM (扫描电子显微镜)",
    "TEM": "TEM (透射电子显微镜)",
    "Probe Card": "探针卡 (Probe Card)",
    "CD-SEM": "CD-SEM (关键尺寸扫描电镜)",
    "ATE": "ATE (自动测试设备)",
    "CP测试": "CP测试 (晶圆测试)",
    "FT测试": "FT测试 (最终测试)",
    
    # ===== 半导体材料 =====
    "SOI硅片": "SOI硅片",
    "Mask": "光掩膜 (Mask)",
    "Mask Blank": "光刻基板 (Mask Blank)",
    "Low CTE玻纤布": "Low CTE玻纤布",
    "EMC": "EMC (环氧塑封料)",
    "MLCC": "MLCC (多层陶瓷电容)",
    "PI薄膜": "PI薄膜 (聚酰亚胺)",
    "LCP": "LCP (液晶聚合物)",
    "PPS": "PPS (聚苯硫醚)",
    "PEEK": "PEEK (聚醚醚酮)",
    "TGV": "TGV (玻璃通孔)",
    "Underfill": "Underfill (底部填充)",
    
    # ===== 算力芯片 =====
    "GPU": "GPU (图形处理器)",
    "CPU": "CPU (中央处理器)",
    "ASIC": "ASIC (专用集成电路)",
    "FPGA": "FPGA (现场可编程门阵列)",
    "MCU": "MCU (微控制器)",
    "NPU": "NPU (神经网络处理器)",
    "DPU": "DPU (数据处理器)",
    "DSP": "DSP (数字信号处理器)",
    "RISC-V": "RISC-V (开源指令集)",
    "SerDes": "SerDes (串行解串器)",
    "CXL": "CXL (Compute Express Link)",
    "HBM控制器": "HBM控制器",
    
    # ===== 高带宽内存 =====
    "HBM": "HBM (高带宽内存)",
    "HBM3": "HBM3 (高带宽内存)",
    "HBM3E": "HBM3E (高带宽内存)",
    "HBM4": "HBM4 (高带宽内存)",
    "DRAM": "DRAM (动态随机存取内存)",
    "DDR5": "DDR5 (第五代内存)",
    "DDR4": "DDR4 (第四代内存)",
    "LPDDR5": "LPDDR5 (低功耗内存)",
    "LPDDR5X": "LPDDR5X (低功耗内存)",
    "GDDR6": "GDDR6 (显存)",
    "SRAM": "SRAM (静态随机存取内存)",
    "NAND Flash": "NAND Flash (闪存)",
    "MRAM": "MRAM (磁阻内存)",
    "ReRAM": "ReRAM (电阻式内存)",
    
    # ===== 网络互联 =====
    "NVLink": "NVLink (英伟达高速互联)",
    "NVSwitch": "NVSwitch (英伟达交换机)",
    "InfiniBand": "InfiniBand (无限带宽)",
    "RoCE": "RoCE (融合以太网)",
    "PCIe": "PCIe (高速扩展总线)",
    "SmartNIC": "SmartNIC (智能网卡)",
    "NIC": "NIC (网络接口卡)",
    "DAC": "DAC (直连铜缆)",
    "AOC": "AOC (有源光缆)",
    
    # ===== 光通信 =====
    "EML": "EML (电吸收调制激光器)",
    "VCSEL": "VCSEL (垂直腔面发射激光器)",
    "DFB": "DFB (分布反馈激光器)",
    "CW Laser": "CW Laser (连续波激光器)",
    "CPO": "CPO (光电共封装)",
    "PIC": "PIC (光子集成电路)",
    "TFLN": "TFLN (薄膜铌酸锂)",
    "EDFA": "EDFA (掺铒光纤放大器)",
    "800G": "800G (光模块)",
    "1.6T": "1.6T (光模块)",
    "FA组件": "FA组件 (光纤阵列)",
    
    # ===== 电力・液冷・数据中心 =====
    "UPS": "UPS (不间断电源)",
    "PDU": "PDU (电源分配单元)",
    "CDU": "CDU (冷量分配单元)",
    "HVAC": "HVAC (暖通空调)",
    "HPC": "HPC (高性能计算)",
    
    # ===== 工业自动化与机器人 =====
    "CNC": "CNC (数控系统)",
    "PLC": "PLC (可编程逻辑控制器)",
    "IIoT": "IIoT (工业物联网)",
    "MES": "MES (制造执行系统)",
    
    # ===== 云・AI应用 =====
    "Azure": "Azure (微软云)",
    "AWS": "AWS (亚马逊云)",
    "Google Cloud": "Google Cloud (谷歌云)",
    "Gemini": "Gemini (谷歌大模型)",
    "TPU": "TPU (张量处理器)",
    "RAG": "RAG (检索增强生成)",
    "MCP": "MCP (模型上下文协议)",
    "Agent": "Agent (智能体)",
    
    # ===== 量子计算 =====
    "QPU": "QPU (量子处理器)",
    "Qiskit": "Qiskit (量子开发套件)",
    
    # ===== 医疗健康 =====
    "ADC": "ADC (抗体药物偶联物)",
    "CAR-T": "CAR-T (嵌合抗原受体T细胞)",
    "GLP-1": "GLP-1 (胰高血糖素样肽-1)",
}
